version: '3.1'

services:

  db:
    build:
        context: .
    restart: always
    ports:
        - 5436:5432
    volumes:
        - pgdata:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: openaq
        POSTGRES_PASSWORD: openaq
        POSTGRES_DB: openaq
        PGUSER: openaq
        PGDATABASE: openaq
        PGPASSWORD: openaq

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000

volumes:
    pgdata: